image: python:3.11

pages:
  stage: deploy
  script:
    - pip install mkdocs mkdocs-materials
    - mkdocs build 
    - mv site public 
  artifacts:
    paths:
      - public
  only:
    - feature/documentation
