site_name: TimeTraceTools 

nav: 
  - Home: index.md 
  - Installation: installation.md 
  - Quick start guide: quick_start.md
  - Features:
    - data_io: data_io.md 
    - data_types: data_types.md 
    - data_processing: data_processing.md  
  - Software design: software_design.md
  - Guidelines for developers: developer_notes.md

  # - Versions: CHANGELOG.md 

plugins:
    - search
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: purple

  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format




